/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 */

plugins {
    java
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.miglayout:miglayout-swing:5.1")
    implementation("org.json:json:20240303")
}

tasks.named<Jar>("jar") {
    manifest {
        attributes["Main-Class"] = "Main"
    }
}